# Generated by Django 4.1.7 on 2023-10-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appUpload',
        ),
    ]
