# Generated by Django 4.1.7 on 2023-10-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_appupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='addImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
