# Generated by Django 4.1.7 on 2023-10-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_addimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='appUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='addImage',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
